# Generated by Django 4.2.26 on 2025-11-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spy_cats', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('cat', models.OneToOneField(blank=True, help_text='One cat can only have one mission at a time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='spy_cats.cat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
